Fix deprecation warnings for python 3.10
django/asgiref pull request #262
Opened 2021-05-20 16:55 UTC by vaartis

asyncio.get_event_loop was marked as deprecated, the documnetation
now refers to asyncio.get_running_loop([1])

asyncio.ensure_future issues a deprecation warning if there is no
running event loop([2]), so use asyncio.run which creates and destroys the
loop itself

asyncio.gather issues a warning if run outside of event
loop (i.e. there is no running event loop)([3]), so wrap it into an
async def

explicit passing of coroutine objects to asyncio.wait is deprecated
since 3.8([4]), so wrap them in asyncio.create_task

plus, add 3.10 to tox.ini

[1]: https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.get_event_loop
[2]: https://docs.python.org/3.10/library/asyncio-future.html#asyncio.ensure_future
[3]: https://docs.python.org/3.10/library/asyncio-task.html#asyncio.gather
[4]: https://docs.python.org/3.10/library/asyncio-task.html#asyncio.wait

2021-05-20 18:05 UTC, carltongibson reviewed
Hi @vaartis, `get_running_loop()` was not added until Python 3.7 so there needs to be a bigger discussion about Python support before we can move to it. I’ve raised it as a possibility on #260. Let’s see what folks say. Thanks.

2021-05-20 18:41 UTC, andrewgodwin requested changes
`asgiref` is required to work on Python 3.6 due to Django and Flask.

2021-05-20 19:39 UTC, andrewgodwin approved these changes
Lovely, I much prefer this. I'll merge it once the CI passes.

2021-05-22 04:02 UTC, merged

2021-05-22 04:03 UTC, andrewgodwin commented
Thanks for this! Were you testing this against Django, Flask, or something else? Due to the nature of the change I'll have to manually run some tests to make sure we didn't introduce subtle breakage and it'd be nice to know if some of those areas are already covered.

2021-05-22 08:40 UTC, vaartis commented
> Thanks for this! Were you testing this against Django, Flask, or something else? Due to the nature of the change I'll have to manually run some tests to make sure we didn't introduce subtle breakage and it'd be nice to know if some of those areas are already covered.

Django, at least the test suite, did pass. However I didn't test anything on 3.6, only 3.8 and 3.10.

2021-05-22 17:21 UTC, andrewgodwin commented
> Django, at least the test suite, did pass. However I didn't test anything on 3.6, only 3.8 and 3.10.

Great, thanks for that. I'm not too worried about 3.6 since this patch barely changes behaviour for it - I'll run a few extra tests with some weird async Django apps I have to make sure and then I'll get this into a release.