Remove unnecessarily complicated backwards compatibility code
django/asgiref pull request #408
Opened 2023-09-15 06:01 UTC by kimvais

`asyncio.iscoroutinefunction` would be needed as a fallback only for Python 3.4 as 3.3 didn't have asyncio and 3.5 introduced `inspect.iscoroutinefunction` 

Also made the 3.12 version check explicit instead of implicit based on the existence of the decorator.

2023-09-15 19:24 UTC, kimvais commented
Well, I'm a strong believer that "Readability counts" is the most important piece of PEP 20 and in my opinion making any code less consistent (and therefore arguably less readable) because some third-party static analysis tool might not be up to speed is counterproductive.

But fair enough, no objection on changing the if clause back to what it was. I guess I got a bit distracted by the bit confusing comment :)

2023-09-16 06:27 UTC, carltongibson approved these changes
This looks OK. 

Folks have been using, and documented examples point to, the `asyncio` import rather than the `inspect` one, so there might be a head scratch here, but I don't suppose it matters. Current advice is "use the shim until 3.12 is minimum version". There's no reason for folks to open the box. 



(Ref the previous discussion, feature detection is better than a hard version check, one might think, but that's been resolved.)

2023-09-16 06:27 UTC, carltongibson commented on asgiref/sync.py
> +# Python 3.12 replaces the _is_coroutine marker with the inspect.markcoroutinefunction decorator.
Wrapping to 79chars?

2023-09-18 06:42 UTC, carltongibson requested changes
Sorry, I made a mistake previously... We can't make this change. `asyncio.iscoroutinefunction()` is **not** equivalent to `inspect.iscoroutinefunction()` prior to Python 3.12, because it performs the additional check for the `_is_coroutine` marker. 

That's why the tests are failing here. (I ran it against Django's test suite to check, and that revealed the same problem. 🤦‍♀️) 

To be honest, I think the comment as written has needed information.

2023-09-20 05:22 UTC, closed without merging